version: '3.8'

services:
  app:
    image: elviajero34/dinnertime:latest
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "3001:3001"
    volumes:
      - ./db/production.sqlite3:/app/db/production.sqlite3
    command: bundle exec rails s -b '0.0.0.0' -p 3001
  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
